title: Hello Python
description: My Personal Stack Problems
author: Seul Lee(이슬)
github: https://github.com/lee-seul
about: Python과 웹 개발에 관심이 많음, 3월 이전에 index페이지 리뉴얼
disqus_shortname: developer-seul
#google_analytics: UA-XXXXXXXX-Y

encoding: UTF-8
enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/blacksangi"
#    - icon: fa-skype
#      link: "#"
#    - icon: fa-twitter
#      link: "https://twitter.com/agusmakmun6"
#    - icon: fa-linkedin
#      link: "#"
#    - icon: fa-stack-exchange
#      link: "#"

#share:
#  twitter_username: agusmakmun6
#  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
#    - text: Projects
#      url: /projects/
    - text: Github
      url: https://github.com/lee-seul
    - text: XML Feed
      url: /feed.xml

url: "https://lee-seul.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
